### ISSUE TITLE
_zsh_cwd_history_histfile_for_cwd:1: command not found: md5

### ISSUE THREAD

**Issue by AntoineD** [ericfreese/zsh-cwd-history#1]
Hi,
I do have md5sum but not md5, where should I get it ?

**Comment by Konfekt** [comment]
Exactly! Was just going to submit this issue myself. OpenSUSE 42.1 neither has `md5`.

The only place that offered `md5` was 

https://www.fourmilab.ch/md5/

where the file had to be untared, unzipped, compiled and put into `$PATH`.

**Comment by mikea** [comment]
@Konfekt it is still not the same md5 the author has used (it doesn't have -q).
Sadly this plugin isn't operable for me either because of this issue (ubuntu).

**Comment by nickmetal** [comment]
@ericfreese Please, can you approve [mikea PR](https://github.com/ericfreese/zsh-cwd-history/pull/3/commits)?

**Comment by bonnebulle** [comment]
same here
cant install https://www.fourmilab.ch/md5/
am on Debian

**Comment by Konfekt** [comment]
Have a look at the fork https://github.com/ceed0/zsh-prioritize-cwd-history
